# -*- coding: utf-8 -*-
"""Adventure_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/BenMacdui/Grinchy-and-Wolfie-s-Python-Code/blob/main/Adventure_game.ipynb
"""

#@title The Adventure game {display-mode: "form"}

from random import randint
import random
import time
from IPython.display import clear_output
import sys
import os


def clear():
    """This function checks whether we are in windows 'nt' or
    and if so uses cls command to clear the sreen all other
    systems, incl. Mac are based on unix and use clear.
    It will clear the screen nicely"""
    os.system('cls' if os.system == 'nt' else 'clear')
    return

#clear the screen before the game starts
clear_output()
clear()


#a little countdown to tell players the game will start soon
for i in range(10,0,-1):
    print(f" Game will start in {i} seconds\r", flush=True)
    time.sleep(1)
    print('\a') # beep
    clear()
print('\a'* 3)
time.sleep(3)

input('Ready? Enter to start')

def bday_check():
    import datetime
    from datetime import date

    a = datetime.date.today()

    mum_date = datetime.date(2022,4,22)
    mum_dleft = mum_date - a
    sam_date = datetime.date(2022,1,27)
    sam_dleft = sam_date - a

    return mum_dleft.days, sam_dleft.days

def bday_Sam():
    import datetime
    from datetime import date
    import time

    a = datetime.date.today()

    sam_date = datetime.date(2022,1,27)
    sam_dleft = sam_date - a
    birthday = sam_date == a
    bigger = sam_date < a
    return birthday, bigger

def riddle():
    import random
    import requests
    url = "https://raw.githubusercontent.com/BenMacdui/Grinchy-and-Wolfie-s-Python-Code/main/test_questions.txt"

    quest = requests.get(url)

    a = quest.text
    x = a.split('--')
    #going through the list and putting 2 list items together into subList
    subList = [x[n:n+2] for n in range(0, len(x), 2)]
    riddle = random.choice(subList)
    #riddle = subList[-4] # for testing answers
    #priints question and answer
    print()
    print('Solve the following riddle \n\n\n' + riddle[0])
    print()
    answer = input().lower().split()
    print()
    x = riddle[1]
    y = x.split()


    if answer[-1] == y[-1]:
        print()
        print('Correct')
        print()
        score = 1
        print()
        print("You can keep the bread, cheese, Haribos and water and I am free too")
        print()
    elif answer[-1] != y[-1]:
        print()
        print('Wrong')
        print()
        st = input('enter if you want to try again or q to quit')
        print()
        count = 0
        if st != "q":
            while count < 2:
                count += 1
                print()
                print(riddle[0])
                print()
                print()
                answer = input().lower().split()
                print()
                x = riddle[1]
                y = x.split()
                if answer[-1] == y[-1]:
                    print()
                    print('correct', + count)
                    print()
                    score = 1 + count
                    print()
                    print(f"You solved the riddle needing {score} tries. \nYou can only take water or Haribos or the bread and cheese. \nWhich one will you choose?")
                    choose = input("enter 1 for bread and cheese or 2 for Haribo or 3 for water. But choose wisely >>>  ")
                    print()
                    print()
                    if choose == '1' or choose == '2':
                        print()
                        print("Wrong choice. You can't live without water for more than 3 days and you will perish out in the wild land.")
                        print()
                        print("That's the end. Thanks for playing. Try again \U0001F600 \n\nGoodbye")
                        break
                    else:
                        print()
                        print("Good choice. Water will give you a chance to survive a bit longer. You need to find food. \n'Here, said the shopkeeper, looking nervously around himself, 'take the Haribo. \nBut be carful not to take them out during daytime. \nAnd now go'")
                        print()
                        print("Goodbye. Thanks for playing. \U0001F600")
                        break
                elif answer[-1] != y[-1]:
                    print()
                    print("Wrong again")
                    print("That's the end. Thanks for playing. Try again \U0001F600 \n\nGoodbye")
                    break

        elif st == 'q':
            print()
            print("Thanks for playing. Try again")
            print()
    else:
        print()
        print("I cannot help you, or I will be condem to work without sleep for ever, \nyou must move on without the food. \n'Here, said the shopkeeper, looking nervously around himself, 'take the Haribo. \nBut be carfule not to take them out during daytime. \nAnd now go'")
        print()
    return
############################################################
def quiz():
    import random
    score = 0
    questions = [["Who chases the seven sisters in the night sky?", "orion"], \
             ["When Lisa was six years old her little sister Lucy was half her age.\
             \nIf Lisa is forty today how old is her sister?", "37"], \
             ["There are two slices of chocolate cake in my cupboard,\
             \none slice is 5/8 of the cake and the other 6/9.\
             \nBring me the bigger slice.\nJust type the either of the number","6/9"],\
             ["You are given 3 positive numbers. You can add these numbers and multiply them together.\
             The result you get will be the same. Which are the numbers?", "1,2,3"],
                ["What can you put between a 7 and an 8 so that the \
                \nresult is greater than 7 but less than 8?", "a decimal point"], \
                ["If A + B = 76 and A - B = 38 \nthen what is the result of A divided by B (/)?","1"],\
                ["I keep sheep, goats and horses. But I can't think how many I have \
                \nat the moment I have all sheep bar three and all goats bar four, \nand all horses bar five \
                 So how many sheep, goats and horses in that order do I have. Just give me the \nnumbers \
                 seperated by commas", "3,2,1"],
                ["I once went to a strange country, I think it was called Germany \nThe language was strange \
                and was in their capital city but forgot the name. \nTell me the capital city of Germany", "berlin"]]
    tries = 3
    while tries > 0:

        question = random.choice(questions)
        print()
        print('Answer the following. ' + question[0])
        print()
        answer = input().lower()
        print()
        if answer == question[1]:
            print('Correct')
            score = score + 1

        else:
            print('Wrong')
            score -= 1
        tries -= 1

    print()
    print(f"You got {score} out of 3 questions right")
    print()
    if score == 2 and score < 3:
        print()
        print("You are free to go, but go you must go cause I still don't trust you.\n \
        go quickly before I change my mind")
        print()
    elif score == 3:
        print()
        print("You are who you said you are, the score proofs it and you can stay or go as you please")
        print()
    else:
        print()
        print("You have tried to deceive me and you will have to work as housmaids for 10 years \nsleeping \
        on he floor for your sins")
        print()
    return
############################################################
def player_mono():
    smilie = '\U0001f600'
    mono = input('Tell me your name please ').lower()
    if mono == 'mum' or mono == 'michelle':
       adult = mono.title()
       print()
       print(f"Hello {adult}, I know you. You are the lovely and most amazing lady who lives in Aviemore, Scotland. \nYour birthday is in {bday_check()[0]} days. {smilie}\nHope you have a good game")
       print()
    elif mono == 'sam' and bday_Sam()[0]:
       child = mono.title()
       print(f"Hello {child}. I know you. You are the smart one {smilie} Today you are 12 years old. Happy Birthday \U0001f389 \U0001f973 \nHope you have a good day and a good game. \U0001f600")
       time.sleep(3)
    elif mono == 'sam' and bday_Sam()[1]:
       child = mono.title()
       print(f"Hello {child}. I know you. You are 12 years old and you are known as the smart one  {smilie} \nHope you have a good game")
    elif mono == 'sam':
       child = mono.title()
       print(f"Hello {child}. I know you. You are almost 12 years old and you are know as the smart one \U0001f600. \nYour birthday is in {bday_check()[1]} days. {smilie} \nHope you have a good game")
       print()

    return
##################################################################
def player_multi():
    smilie = '\U0001f600'
    print()
    name_player_one = input('Tell me your name please ').lower()
    print()
    name_player_two = input("Tell me your name please, player number two: ").lower()
    print()
    first = name_player_one.title()
    second = name_player_two.title()
    if first =='Sam' and bday_Sam()[0]:
        print(f"Hello {first}. I know you. You are the smart one {smilie} Today you are 12 years old. Happy Birthday \U0001f389 \U0001f973 \nHope you have a good day and a good game. \U0001f600")
        time.sleep(3)
        print()
        print("*"*80)
        print()
        print(f"I know you too, {second}. You are the lovely and most amazing lady who lives in Aviemore, Scotland \U0001f604 \nYour birthday is in {bday_check()[0]} days.{smilie} \nHope you have a good game")
    elif first =='Sam' and bday_Sam()[1]:
            print(f"Hello {first}. I know you. You are 12 years old and you are known as the smart one  {smilie} \nHope you have a good game")
            print()
            print()
            print("*"*80)
            print()
            print(f"I know you too, {second}. You are the lovely and most amazing lady who lives in Aviemore, Scotland \U0001f604 \nYour birthday is in {bday_check()[0]} days.{smilie} \nHope you have a good game")

    elif first == 'Sam':
        print()
        print(f"Hello {first}. I know you. You are almost 12 years old and you are know as the smart one \U0001f600. \nYour birthday is in {bday_check()[1]} days. {smilie} \nHope you have a good game")
        print()
        print()
        print("*"*80)
        print()
        print(f"I know you too, {second}. You are the lovely and most amazing lady who lives in Aviemore, Scotland \U0001f604 \nYour birthday is in {bday_check()[0]} days.{smilie} \nHope you have a good game")
        print()

  #############################################################
    if second == "Sam" and bday_Sam()[0]:
        child = second.title()
        print(f"Hello {child}. I know you. You are the smart one {smilie} Today you are 12 years old. Happy Birthday \U0001f389 \U0001f973 \nHope you have a good day and a good game. \U0001f600")
        time.sleep(3)
        print("*"*80)
        print()
        print(f"I know you, {first}. You are the lovely and most amazing lady who lives in Aviemore, Scotland  \U0001f604 \nYour birthday is in {bday_check()[0]} days. {smilie} \nHope you have a good game")
        print()
        print()
    elif second ==  "Sam" and bday_Sam()[1]:
        child = second.title()
        print(f"Hello {child}. I know you. You are 12 years old and you are known as the smart one  {smilie} \nHope you have a good game")
        print()
        print("*"*80)
        print()
        print(f"I know you, {first.title()}. You are the lovely and most amazing lady who lives in Aviemore, Scotland  \U0001f604 \nYour birthday is in {bday_check()[0]} days. {smilie} \nHope you have a good game")
        print()
    elif second == "Sam":
        child = second.title()
        print()
        print(f"Hello {child}. I know you. You are almost 12 years old and you are known as the smart one. \nYour birthday is in {bday_check()[1]} days. {smilie} \nHope you have a good game")
        print()
        print("*"*80)
        print()
        print(f"I know you, {first.title()}. You are the lovely and most amazing lady who lives in Aviemore, Scotland  \U0001f604 \nYour birthday is in {bday_check()[0]} days. {smilie} \nHope you have a good game")
        print()
        print()
    return

############################################################
players=""
while players != '1' and players != '2':
  print()
  players = input("One or two players? Enter 1 or 2: ")
  print()
  print()
if players == '1':
  player_mono()
elif players == '2':
  player_multi()



print()
print('_'*60)
print()
print('Are you ready to play? ')


print()
print()
input("enter to continue")

print()
print()
##############################################################
def word_list():
    import requests

    url = "https://raw.githubusercontent.com/BenMacdui/Grinchy-and-Wolfie-s-Python-Code/main/German_words.txt"
    url_1 = "https://github.com/BenMacdui/Grinchy-and-Wolfie-s-Python-Code/blob/main/German_text2.txt"

    result = requests.get("https://raw.githubusercontent.com/BenMacdui/Grinchy-and-Wolfie-s-Python-Code/main/German_words.txt")
    result2 = requests.get("https://raw.githubusercontent.com/BenMacdui/Grinchy-and-Wolfie-s-Python-Code/main/German_text2.txt")


    g_list_1 = result.text
    g_list_2 = result2.text
    for i in g_list_1:
        x = g_list_1.split(',')
    for i in g_list_2:
        y = g_list_2.split(',')




    g_list = dict(zip(x, y))
    g_list
    return g_list


def German_word():
    import random

    correct = 0
    wrong = 0
    tries = 3
    while tries > 0:
        tries -= 1
        keywlist = list(word_list().keys())
        random.shuffle(keywlist)

        for keyword in keywlist:
            display ="{}"
        print("")
        #print(display.format(keyword))

        userinput_answer = input(f"Tell me the English word for: {keyword}: ").lower()
        #print(g_list[keyword])
        print("")

        if userinput_answer == (word_list()[keyword]).lstrip():
            print("Correct \U0001f601")
            correct += 1
        else:
            print("Wrong \U0001F612")
            wrong += 1
            print("*" * 25)
    print()
    print('*'*25)
    display = "Score: {} correct and {} wrong"
    print(display.format(correct,wrong))
    print('*'*25)

    print()
    if correct > 2 or correct == 2:
        print('The ladies got it right and were allowed into the house')
    else:
        print('The ladies were turned into stone')
    return
 ####################################################################
def getSecretNum():

    """Returns a string made up of NUM_DIGITS unique random digits."""
    numbers = list('0123456789')  # Create a list of digits 0 to 9.
    random.shuffle(numbers)  # Shuffle them into random order.

    # Get the first NUM_DIGITS digits in the list for the secret number:
    secretNum = ''
    for i in range(NUM_DIGITS):
        secretNum += str(numbers[i])
    return secretNum
 #########################################################
def getClues(guess, secretNum):

    """Returns a string with the pico, fermi, bagels clues for a guess
     and secret number pair."""
    if guess == secretNum:
        return 'You must have a lucky star!'

    clues = []

    for i in range(len(guess)):
        if guess[i] == secretNum[i]:
            # A correct digit is in the correct place.
            clues.append('Fermi')
        elif guess[i] in secretNum:
          # A correct digit is in the incorrect place.
            clues.append('Pico')
    if len(clues) == 0:
        return 'Bagels'  # There are no correct digits at all.
    else:
     # Sort the clues into alphabetical order so their original order
     # doesn't give information away.
        clues.sort()
     # Make a single string from the list of string clues.
        return ' '.join(clues)
################################################################

print()
print("""Two lovely ladies skipped along a field of flowers when they suddenly
saw a mean pirate at the horizon with his pet wolf.

The ladies didn't know what the pirate was up to but he looked mean.

There is a cave on their right side which looked dark and has a spider dangling from it's entrance.

On the left hand side, on the other hand, there is a house with a welcoming face of a woman in the window, watching them.

What should the ladies do? Shall the ladies run to the cave or the house? """)
print()
print()

choice =""
while choice != 'l' and choice != 'r':
    choice = input('do they go left to the house or the cave? Enter l for house,  or r for cave: ')
print()
print()
if choice == 'l':
    clear_output()
    clear()


    print("""the two lovely ladies go to the house with the friendly face.

          But the woman in the house doesn't want to open the door as she fears
          that the two lovely ladies turn out to be two evil witches that haunt the woman in the house.

          So she sets them a test, as she knows the witches wouldn't be able to answer the test.

          She says: The evil witches speak a strange language but not ours. But while we can understand
          what they are saying they cannot understand us.

          So you need to tell me the English translation of a word chosen by my parrot at random, only then can I be sure you are not
          evil witches.

          But if you don't know the translation of the word you will be turned to stone.
    """)
    time.sleep(10)
    print()
    print()
    input('Press enter to continue')
    German_word()
    print()
    print()
    input('press enter to continue')
    print()
    print("""But once in the house the friendly face turned a little icy.

'If you think you can just come in here and eat all my food and sleep in my bed and use up all my coal and wood to warm yourself you have another thing coming.

I think you two are up to no good and I need more evidence that you really are two lovely ladies and not just pretend to be.

Only lovely ladies would know the answers to the following question and you need to answer 2 out of 3 correctly.

I have written each question on a piece of paper and my parrot will choose a question at random

You have to answer it correctly or you will be chained to the house to work as housmaid for 10 years.""")

    print()
    print()
    input('Press enter to continue')
    print()
    quiz()
    print()

elif choice == 'r':
    clear_output()
    clear()

    print("""The two lovely ladies run to the cave where the spider danlged from the entrance and the inside
    was very, very dark and scary. But the two lovely ladies had no choice, as the pirate was approaching
    really fast.

    The spider looked scary too. It had nine eyes and huge fangs and 9 hairy legs.
    The hairs were like darts and could pierce your heart in an instance.

    It looked at the two lovely ladies with her nine eyes and said:

    So you came here to hide, eh?

    The two lovely ladies noddedd their head, as they were too scared to say something.

    The spider starred at them and for a moment the two lovely ladies thought the spider would jump
    and bite them but to their surprise the spider said.

    'You come to the right place and grinned.'

    Inside there is a lovely fire and some food and Haribos that will keep you cosy and warm and you no go hungry while you hide.

    But, added the spider, inside lives a friendly ogre who loves nothing more than playing Rock, Sissors and
    Paper. He likes to play but if you loose he will eat you but if you win or if it is a draw
    he will let you stay as long as you like and no-one will find you.

    Faced with either confronting the mean pirate and his pet wolf or the ogre and a nice fire and a warm meal
    the lovely ladies walked to the entrance of the dark cave.

    But here they encountered an invisible barrier.""")
    input("enter to continue")
    clear()
    print()
    NUM_DIGITS = 3  #
    MAX_GUESSES = random.randint(1,10)  #
    print(''' Hi, said a female voice, I am a living lock. Invisible but you can't go through me unless you unlock me.

    You have to guess the numbers, the clues I give you are purely based on logic. I love logic.

    I would give you endless tries but inside me lives another me that is a little develish and so she will choose the tries and sometimes she feels generous and sometimes she feels a bit mean.

    If you like logic too it will be easy to open the locks. But if you use flower power logic, it won't be

    I am thinking of a {}-digit number with no repeated digits.
    Try to guess what it is. Here are some clues:''')
    input("enter to continue")
    clear()
    print('''
    When I say:    That means:

    Pico         One digit is correct but in the wrong position.
    Fermi        One digit is correct and in the right position.
    Bagels       No digit is correct.

    For example, if the secret number was 248 and your guess was 843, the
    clues would be Fermi Pico.'''.format(NUM_DIGITS))
    print()
    print()


    while True:  # Main game loop.
        # This stores the secret number the player needs to guess:
        secretNum = getSecretNum()
        print('I have thought up a number.')
        if MAX_GUESSES <= 5:
            print("I am not in a good mood. You have {} guesses to get it.".format(MAX_GUESSES))
        else:
            print(' I feel generous today. You have {} guesses to get it.'.format(MAX_GUESSES))

        numGuesses = 1

        while numGuesses <= MAX_GUESSES:
            guess = ''
            # Keep looping until they enter a valid guess:
            while len(guess) != NUM_DIGITS or not guess.isdecimal():
                print('Guess #{}: '.format(numGuesses))
                guess = input('>>> ')

            clues = getClues(guess, secretNum)
            print(clues)
            numGuesses += 1

            if guess == secretNum:
                print("you can enter the cave")
                time.sleep(3)
                break  # They're correct, so break out of this loop.
            if numGuesses > MAX_GUESSES:
                print('You ran out of guesses.')
                print('The answer was {}.'.format(secretNum))
                print()
                print('You were not able to unlock me so you must move on and freeze to ice')        # Ask player if they want to play again.
                print('The two loveley ladies had no other choice but to leave')
                time.sleep(3)
                sys.exit()
        break


    print()
    print()
    input("enter to continue")
    clear()
    print("""As soon as they entered the spider closed a door behind them and a fire began to roar and a scorpion
    carried snacks and placed them on a table in front of them. A slimy fat frog licked at some Haribo and watched TV

    Not far from the table sat a big green ugly looking ogre who when smiled had black teeth and a blue tongue
    and his nose was all crooked and his eyes were crossed when he looked at them.

    He said: Welcome to my home. Eat and drink as much as you like.

    But when you done we play a game of Rock, Sissors and Paper: Best out of 3. Loose and I eat you
    Win and you can stay. He laughed and the ladies shivered. But they had no choice.

    So the two lovely ladies nodded and picked at some food. The slimy frog pushed a bowl of Haribos
    to them after he had taken a couple but the two lovely ladies declined.

    'You no like Haribos?' the slimy fat frog asked, licking his fingers and grabbed some more
    'You should try some they good'.
    'No thank you' replied the two lovely ladies, 'we are done'.

    'If you done eating'said the orgre, and rubbed his hands: Let's play Rock, Sissors and Paper""")
    print()
    print()
    time.sleep(10)
    print()
    print()
    input('press enter to continue')

# create a list of play options
    t = ['rock', 'sissors', 'paper']

#assign the ogre random play



# We set our counters to zero and then add into them to keep
# a tally on the score
    ogrecount = c = 0
    playercount = p = 0
    tie = 0


# set run to true so that it runs while true, till interrupted with q

    run = 3
# the main loop: this will run till the user inputs q (for quit)
    while run > 0:
        ogre = t[randint(0,2)]
        run -= 1

#after the beginning of the main loop (here a while loop),
# we clear all output from before. It makes for a nicer screen


# turn all input into lower case alphabet with .lower() function,
#just in case a user has all capitals on.

        player = input('rock, sissors, paper? ').lower()


#after our input we get our conditionals. This is to evaluate the options
# what did the ogre choose, what did the player choose, who wins.

        if player == ogre:
            print('ogre chose', ogre, )
            print("tie")
            print('*'*40)
            tie += 1
            time.sleep(2)

        elif player == 'rock':
            if ogre == 'paper':
                print('ogre chose', ogre, )
                print('\nthe two lovely ladies loose', ogre, 'covers', player)
                c += 1
                print('*'*40)
                time.sleep(2)
            else:
                print('ogre chose', ogre, )
                print('the two lovely ladies win.', player, 'smashes', ogre)
                p += 1
                print('*'*40)
                time.sleep(2)

        elif player == 'paper':
            if ogre == 'sissors':
                print('ogre chose', ogre,)
                print('\nthe two lovely ladies loose', ogre, 'cuts', player)
                c  += 1
                print('*'*40)
                time.sleep(2)
            else:
                print('ogre chose', ogre, )
                print('the two lovely ladies win', player, 'covers', ogre)
                p += 1
                print('*'*40)
                time.sleep(2)

        elif player == 'sissors':
            if ogre == 'rock':
                print('ogre chose', ogre,)
                print('\nthe two lovely ladies loose', ogre, 'smashes', player)
                c += 1
                print('*'*40)
                time.sleep(2)
            else:
                print('ogre chose', ogre, )
                print('the two lovely ladies win', player, 'cut', ogre)
                p += 1
                print('*'*40)
                time.sleep(2)

# If you typed in q the ogre will break the loop and end the game
        elif player == 'q':
          print("Thanks for playing")
          break

# if the user accidentially made a typo we tell the user then go back to the
# input after 2 seconds
        else:
            print('That is not a valid choice. Check your spelling')
        time.sleep(2)

        ogre = t[randint(0,2)]


# Once we broken out of the loop we display the final score
    print()

    if p < c:
        print("The Ogre won and ate the two lovely ladies")


    else:
         print("The two lovely ladies win and get to live a happy life ever after")
         print()
         input("press enter to continue")
         print()
         print("""After a while the Ogre started to think that the two lovely ladies
     had cheated at the game, the slimy fat frog had whispered lies into the Ogres
     ear and he got really angry.

The two lovely ladies were just able to escape the cave when the door
opened for the scorpion to go out to get some more food

The two lovely ladies run to the hills behind a wood.

They didn't know where they were when they saw a shop in the distance. The went to have a closer look.

It was a shop that sold everything but mainly food and as they
were really hungry and thirsty the went inside.

But while inside the discovered they had no money.

Inside the shop worked the shopkeeper. The shopkeeper had to wear
glasses from looking too much at price signs that had really small
writing on it.

He hated his glasses.

He looked over the rim of his glasses at the two lovely ladies.

The two lovely ladies wonder about the shop and then when the
shopkeeper wasn't looking took some cheese and bread and a bottle
of water and run to the door.

But the door was guarded by the shopkeepers dog, which growled
viciously at the two lovely ladies.

The shopkeeper, who had heard the commotion, came running to the door
and said: 'So we have some thieves, eh, hand over the goods'.

The two lovely ladies sobbed and hand over the
bread and cheese and water. 'We have no money', they trembled
'and we are lost and the mean pirate and his pet wolf are after us'.

The shopkeeper's face which had looked pretty grim and angry, soften
a little, as he had a big heart really, but there so many
witches about in this part that he found it heart to trust anyone
tho the two lovely ladies looked quite innocent.

I can let you have the food, if you help me out.
I am condemned to work in this shop for all eternity
as some sorcerer has put a spell on me and unless I can solve a riddle
he gave me I cannot leave here.

If you can help me out you can have the food and I am free
to leave too.""")
         print()
         input('press enter to continue')
         print()

         riddle()

         print()
         print("The story will continue")
